config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  Rails.application.routes.draw do
    resources :users
    resources :articles do
      resources :comments
      resources :supports
    end
    root 'welcome#index'
  end

  get 'login', :controller => 'users', :action => 'login'
  post 'login', :controller => 'users', :action => 'login'
  get 'logout', :controller => 'users', :action => 'logout'
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  has_many :supports
  mount_uploader :picture, PictureUploader
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/support.rb
class Support < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
  belongs_to :comment
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  has_many :comments
  has_many :supports
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_filter :verify_access, except: [:index]
	def verify_access
    if session[:current_user].nil?
      @hint = "Verify access failed, log in first please."
      redirect_to :controller => 'users', :action => 'login'
=begin
      authenticate_or_request_with_http_basic do |name, passwd|
        t = User.find_by_name(name)
        login_status = (t.nil?) ? false : ((passwd == t.password) ? true : false )
        if login_status
          session[:current_user] = t
          return true
        else
          @hint = "User name or Password is not right."
          return false
        end
      end
=end
    else
      #username = User.find_by_name(session[:current_user]["name"])
    end
	end

	def new
		@article = Article.new
	end

	def create
		#render plain: params[:article].inspect
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])

	    if @article.update(article_params)
		    redirect_to @article
  	    else
    		render 'edit'
  		end
	end

	def show
		@article = Article.find(params[:id])
	end

	def destroy
	  @article = Article.find(params[:id])
 	  @article.destroy

  	  redirect_to articles_path
	end

	def index
		#@articles = Article.all
	    @articles = Article.order("title").page(params[:page]).per(10)
	    @articles.each do |a|
	      puts a["id"]
	      a.title = "[#{a.title}]"
	    end
	    @login_stauts = session[:current_user].nil?

    @pie_data = [{"name" => "a", "age" => 4}, {"name" => "b", "age" => 1}, {"name" => "c", "age" => 5}]
	end

	private
	def article_params
		params.require(:article).permit(:title, :text, :picture)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/supports_controller.rb
class SupportsController < ApplicationController
  def create
    #@user = User.find_by_name(session[:current_user]["name"])
    @article = Article.find(params[:article_id])
    @support = @article.supports.create
    
    redirect_to article_path(@article)
  end

  def index
    redirect_to article_path(@article)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
=begin
	USER_NAME, PASSWORD = "dhh", "secret"
	#http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :login]
=end
  before_filter :verify_login, except: [:login]
  def verify_login
    @login_stauts = session[:current_user].nil?
    #puts "=====================\n#{@login_stauts}\n====================="
  end
=begin
	before_filter :verify_access, except: [:index, :login]
	def verify_access
    if session[:current_user].nil?
      authenticate_or_request_with_http_basic do |name, passwd|
        t = User.find_by_name(name)
        (t.nil?) ? false : ((passwd == t.password) ? true : false )
      end
    end
	end
=end
	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		@h = '0.0'

		if @user.save
			@h = "Regedit OK"
			redirect_to @user
		else
			@h = "Regedit failed"
			render 'new'
		end
	end
  
	def login
 		unless request.get?
       	 	@hint = "ok"
        	@user = User.find_by_name(params[:user][:name])
        	if @user.class == NilClass
          		@hint = 'Login faild. Unregisted Username.'
        	elsif @user.password == params[:user][:password]
          		@hint = "Welcome back, "
              session[:current_user] = @user
          		redirect_to :controller => 'users', :action => 'index'
        	else
          	@hint = "Login failed, please check up you info"
        	end
    	end
	end

  def logout
    session[:current_user] = nil
    #puts "=====================\n#{session[:current_user].class}\n====================="
    redirect_to :controller => 'welcome', :action => 'index'
  end

	def show
    @hint_show = @h
		@users = User.find(params[:id])
	end
	def index
		@users = User.all
	end
	private
	def user_params
		params.require(:user).permit(:name, :password)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/supports_helper.rb
module SupportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "edit.html" %>

<h3>Editing article</h3>

<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "index.html" %>

<p>
<%= @hint %>
</p>
<h2>Listing articles</h2>
 <%= link_to 'Back to Homepage', controller: 'welcome' %>
 <%= link_to 'New article', new_article_path %>
<% if @login_stauts %>
 <%= link_to 'Login', login_path %>
 <%= link_to 'Register', new_user_path %>
<% else %>
  <%= link_to 'Logout', logout_path %>
<% end %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Picture</th>
    <th colspan="4"></th>
  </tr>
 <div id="articles">
  <% @articles.each do |article| %>
    <tr>
    <div class="name">
      <td><%= article.title %></td>
      <td><%= article.text %></td>
    </div>
    <div class="picture">
      <td><%= image_tag article.picture %></td>
    </div>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
 </div>
    <%= paginate @articles %>
</table>


<div id="container" style="width: 600px; height: 400px"></div>​
<script type="text/javascript" charset="utf-8">
  $(function () {
    new Highcharts.Chart({
        chart: {
            renderTo: 'container',
            //alignTicks: false,
            type: 'line'
        },
        title: {
          text: "Students"
        },
        xAxis: {
          categories: <%= raw @pie_data.map {|stu| stu["name"]}.inspect %>,
          title: {
            text: "Name"
          }
        },
        yAxis: [{
            title: {
                text: 'age'
            },
            gridLineWidth: 1
        }],
        tooltip: {
            formatter: function() {
                return '<b>'+ this.series.name +'</b><br/>'+
                    this.x +': '+ this.y;
            }
        },
        series: [{
            data: <%= @pie_data.map {|stu| stu["age"]}.inspect %>
        }]
    });
});​
</script>

app/views/articles/new.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "new.html" %>

<%= form_for [@user, @user.articles.build], url: users_articles_path do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
   <p>
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "show.html" %>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<p>
  <strong>Picture:</strong>
  <p>
   <%= image_tag @article.picture %>
  </p>
</p>

<%#= button_to "Yes: #{@article.supports.count}", {:controller => "articles", :action => "add_support"} %>
<%= button_to "Yes: #{@article.supports.count}", article_supports_path(@article, @user) %>

<h2>Comments</h2>
<% @article.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>
<%= link_to 'Edit', edit_article_path(@article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "index.html" %>
<p>
<%= link_to 'Back to Homepage', controller: 'welcome' %>
<% if @login_stauts %>
 <%= link_to 'Login', login_path %>
 <%= link_to 'Register', new_user_path %>
<% else %>
  <%= link_to 'Logout', logout_path %>
<% end %>
</p>

<h1><%#= @login_stauts %> </h1>

<h2>Listing users</h2>
<table>
  <tr>
    <th>Name</th>
    <th>Password</th>
    <th colspan="3"></th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.password %></td>
    </tr>
  <% end %>
</table>

app/views/users/login.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "login.html" %>


<p>
<%= @hint %>
</p>
<%= form_for :user, :url => {:action => 'login'} do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.submit 'Login' %>
  </p>
<% end %>
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "new.html" %>
<%= form_for :user, url: users_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "show.html" %>
<%= @hint_show %>
<p>
<%= link_to 'Back', users_path %>
</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to 'Users', controller: 'users' %>
<%= link_to 'Articles', controller: 'articles' %>